apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ve53929o9-go 
  janus-idp.io/tekton: ve53929o9-go
  backstage.io/kubernetes-id: ve53929o9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ve53929o9-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  