apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ve53929o9-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ve53929o9-go 
  name: ve53929o9-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ve53929o9-go 
